Esri/esri-leaflet-vector

- debug/sample.html
- package.json
- profiles/base.js
- profiles/production.js
- src/Basemap.js
resolves Esri/esri-leaflet/issues/861
steps to repro:
1. open http://esri.github.io/esri-leaflet/examples/vector-basemap.html
2. switch to Topographic, Gray, Dark Gray
3. basemap will fail to draw, errors regarding web request failures to malformed urls
> not all vector tile json denote glyphs/sprites using relative paths now

- README.md
* Updated leaflet js and css from beta to v 1.0 
* Update esri-leaflet js to 2.0.3 (2.0.2 returned ```Uncaught TypeError: esriLeaflet.Util.setEsriAttribution is not a function```)
> Fix dependency links in readme

- CHANGELOG.md
- README.md
- debug/sample.html
- package.json
- src/Layer.js
- src/Util.js
* using [`jgravois/mapbox-gl-leaflet#indexed-vector-sources`](https://github.com/jgravois/mapbox-gl-leaflet/tree/indexed-vector-sources) as new wrapped dependency
* bumped to leaflet `1.x`
> 1.0.4 release prep

- debug/sample.html
- src/Util.js
resolves #20 
apparently ArcGIS Pro generated vector tiles demarcate the url of their tilemap (if present) without the leading slash, unlike our hosted tilesets.
https://basemaps.arcgis.com/v1/arcgis/rest/services/World_Basemap/VectorTileServer?f=json
```js
{
"currentVersion": 10.4,
"name": "Streets",
"tileMap": "/tilemap"
}
```
https://tiles.arcgis.com/tiles/znO8Hz1SuVVohYhZ/arcgis/rest/services/VectorTiles_Streetmap/VectorTileServer?f=json
```js
{
"currentVersion": 10.41,
"name": "VectorTiles_Streetmap",
"tileMap": "tilemap"
}
```
> make sure to format tileMap urls appropriately

- README.md
- debug/sample.html
- package.json
- profiles/base.js
- profiles/debug.js
- profiles/production.js
- src/Basemap.js
also introduces support for `v2` basemaps
resolves #31, #39, #43 (and hopefully #22)
1. `npm install && npm start`
2. http://localhost:8765/debug/sample.html (which includes a new script tag for mapbox-gl)
in refactoring the build system i noticed that the drawing behavior when you load the latest version of `mapbox-gl` is less glitchy and overall more visually appealing. the downside is that it logs lots of messages to the console, attempts to fetch tiles from our indexed services that were never cached and is incapable of loading a couple of the `v2` basemaps.
the benefit of the new approach is that if any developers don't like the new behavior, we can commit a built version of our stale fork up for them to use instead. either way its a breaking change, but i can live with that if folks …
> make mapbox-gl an external dependency and add more explicit disclaimer

- debug/sample.html
- package-lock.json
- src/Basemap.js
while i was in here i finally figured out what was going on with the broken `v2` basemaps. the problem wasn't anything in the code. there were issues in a few of the style files that trigger `mapbox-gl-js` validation errors'.
to workaround the issue, i made copies of two and patched them manually.
> Error: layers[33]: duplicate layer id "Parcel", previously used at line undefined
i [fixed this one](http://www.arcgis.com/home/item.html?id=7a6bf0e8cb5a418085e66c0485e74d19) by changing the second one to `"id": "ParcelFill"`.
> Error: layers[74].paint.line-width.stops[2][0]: stop domain values must appear in ascending order
i [fixed this one](http://www.arcgis.com/home/item.html?id=93554006894c45a88136127535878fca) by reordering the stops to ensure the zoom levels continually increase. …
> add new esri openstreetmap vector basemap and bump all others to v2

- src/Util.js
right now we start seeing 404s even in places like NYC.
this is a lazy approach to support deep zoom only in areas with good feature density.
> cap native zoom at 15

- debug/sample.html
- package-lock.json
- src/Basemap.js
Updates to sample/debug html file.  Added some basemaps that may or may not be useful.  
I think there are some linting issues, involving my lack of ability to fix simple index/spacing issues in Adobe Brackets.
> Agol basemap integration

- src/Util.js
for some sources, e.g Esri's world contour service at https://basemaps.arcgis.com/arcgis/rest/services/World_Contours_v2/VectorTileServer , the layout property does not exist. As a result the plugin throws an error and we can't currently add the service to a map.
> check if layer layout property exists before accessing

- .eslintrc.js
- examples/contour.html
- package.json
- spec/VectorBasemapLayerSpec.js
- src/Util.js
This should resolve https://github.com/Esri/esri-leaflet-vector/issues/72 allowing for non-esri sources. See the included example.
> add support for items with non-esri source names

- CHANGELOG.md
- README.md
- src/Util.js
- src/VectorTileLayer.js
closes #94 
An example of what this would look like in the FF dev console:
Some inspiration was drawn from: https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-SpatialReference.html#isWebMercator
You can test a demo page with:
`L.esri.Vector.vectorTileLayer("https://services.geodataonline.no/arcgis/rest/services/GeocacheVector/GeocacheBasis/VectorTileServer").addTo(map);`
> 94-non-web-merc-warning

- CHANGELOG.md
- README.md
- spec/VectorTileLayerSpec.js
- src/Util.js
- src/VectorTileLayer.js
Please see commit history and new README documentation for more details.
resolves #88
> 88-enterprise-support

- src/MapBoxGLLayer.js
fixing issue where the esri-leaflet-vector layer was offset incorrectly when zooming out to levels 0 or 1, #125 
I discovered that they experienced and fixed this same issue in mapbox-gl-leaflet, so this PR is porting over those fixes:
- https://github.com/mapbox/mapbox-gl-leaflet/pull/130
- https://github.com/mapbox/mapbox-gl-leaflet/pull/134
> fixed offset issue

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/stale.yml
Added a similar issue type template and stalebot configuration from what Esri Leaflet uses https://github.com/Esri/esri-leaflet/tree/master/.github
> issue type templates and stalebot config from esri-leaflet

- src/VectorBasemapLayer.js
This PR addresses #133, adding "Powered by Esri" to a portal id-referenced `VectorBasemaplayer`.
> 133 - Add "Powered by Esri" to portal id-referenced VectorBasemapLayer source.

- README.md
- examples/contour-dev.html
- examples/custom-vtl-dev.html
- examples/gallery-dev.html
- examples/quickstart-dev.html
- examples/quickstart-prod.html
- index.d.ts
- package-lock.json
- package.json
- profiles/debug.js
- profiles/production.js
- src/MaplibreGLLayer.js
- src/VectorBasemapLayer.js
- src/VectorTileLayer.js
#139 
Switched to using [maplibre-gl-js](https://github.com/maplibre/maplibre-gl-js), using [maplibre-gl-leaflet](https://github.com/maplibre/maplibre-gl-leaflet) as inspiration. 
Some notes:
- This still only supports Web Mercator projection since maplibre only supports that at this time. Getting to this [is on their roadmap](https://roadmap.maplibre.org/c/91-custom-coordinate-system-epsg-non-mercator-projection).
- `getOpacity` and `setOpacity` are not in maplibre-gl-leaflet - I could not remember if we have added that intentionally in our version or not. [I removed it](https://github.com/Esri/esri-leaflet-vector/pull/141/files#diff-3f514e068697c8df07638716f1c0ebe08329ee0b5e15d993d4d89fb2c004d4b4L94-L102), but if it was serving a specific purpose we should probably leave it in.
- Same …
> Switch to use Maplibre GL JS

- examples/contour-dev.html
- examples/custom-vtl-dev.html
- examples/gallery-dev.html
- examples/quickstart-dev.html
As of v2.3.0 of maplibregl-js, the `version` property is now populated: https://github.com/maplibre/maplibre-gl-js/pull/1471  , so I'm adding this back to our example files to aid in debugging.
> maplibregl.version now supported

- spec/VectorBasemapLayerSpec.js
- spec/VectorTileLayerSpec.js
- src/Util.js
This PR addresses #107 by preferring `minLOD` and `maxLOD` in the service where we find it. From my conversations with the JS API and vector tile teams `minLOD` and `maxLOD` define the upper and lower zooms for which tiles have been cooked. MapLibre will display zooms greater then the `maxLOD`/`maxzoom` by over-scaling the tiles.
Re: #107
> Fix #107 by using minLOD/maxLOD

- examples/quickstart-dev.html
- spec/VectorTileLayerSpec.js
- src/Util.js
- src/VectorTileLayer.js
#146 
@patrickarlt please review. A few thoughts that I could use your feedback on:
1. I have not added a unit test for the error emit - I tried to set it up but could not figure out how to mock an invalid URL with sinon
2. Is the name of the event (`load-error`), what we want?
- I guess we want to add this to the documentation too .... do we need to add an "Events" section here https://developers.arcgis.com/esri-leaflet/api-reference/layers/vector-layer/#constructor ?
---
update: Here's how I am testing: add this to `quickstart-dev.html` and go through each cases uncommenting it:
- expected: a `console.log('error'` should happen in each case.
```
var map = L.map("map", {}).setView([34.0522, -118.2437], 15);
// CASE 1 - WRONG VECTORTILELAYER ITEMID
// const overlay = new …
```
> fire load-error

- src/EsriLeafletVector.js
The way the export of version is structured when this package is imported, the following build error can occur:
```
./node_modules/esri-leaflet-vector/src/EsriLeafletVector.js:1:0-53 - Error: Should not import the named export 'version' (reexported as 'VERSION') from default-exporting module (only default export is available soon)
```
Specifically I'm seeing this in an Nx +  Angular 15 monorepo environment when building in SSR, but I'm certain others are seeing similar issues caused by this export syntax.
> update export of package version

- src/EsriLeafletVector.js
We are wanting to implement printing in our application using [this plugin](https://github.com/Igor-Vladyka/leaflet.browser.print), and one of the things that this plugin does is a layer cloning process.  While cloning the `VectorBasemapLayer` does generate the `MaplibreGLJSLayer`, it also throws a warning that it cannot identify this layer.  However, if the `MaplibreGLJSLayer` were exposed this would not be an issue.
Upon looking through the code I could not identify a reason why `MaplibreGLJSLayer` should not be exposed.
> Expose MaplibreGLJSLayer Variable

- README.md
- src/VectorTileLayer.js
It was discovered that printing maps rendered with `esri-leaflet-vector` does not work in Firefox.
An issue was created [here](https://github.com/Esri/esri-leaflet-vector/issues/198).
This PR fixes that issue by allowing the user to set `preserveDrawingBuffer` to `true`, which resolves the issue.  It is set to `false` by default in the `maplibre-gl-js` project in the `scr/ui/map.ts` file for performance optimizations.  Adding the ability for a user to toggle this value through `esri-leaflet-vector`, but maintaining a default of `false` will help users who want to provide printing capabilities, while maintaining the performance optimization for those who do not have this need.
> Allow users to set preserveDrawingBuffer in the options

- package-lock.json
- package.json
I've updated the dependency to v3.3.1, which happens to be the latest and also ran the tests. The results are attached below. Please let me know if I'm missing anything else since this is my very first time contributing to an open-source repo! :)
* Fixes issue #194 
Test results after upgrading the maplibre-gl dependency to v3.3.1:
> updated maplibre-gl dependency to v3.3.1, passing all tests

- examples/languages.html
- examples/rtl-language.html
- package.json
- src/EsriLeafletVector.js
- src/MaplibreGLLayer.js
* Adds support for RTL language labels by exposing the maplibre [`setRTLTextPlugin`](https://maplibre.org/maplibre-gl-js/docs/API/classes/default/#setrtltextplugin) method.
* Adds an example showing how to use it:
```
// Support RTL languages such as Arabic and Hebrew
L.esri.Vector.setRTLTextPlugin('https://unpkg.com/@mapbox/mapbox-gl-rtl-text@0.2.3/mapbox-gl-rtl-text.js');
```
#206/#204
> add rtl support and example #206

- src/MaplibreGLLayer.js
Related to Issue [#210](https://github.com/Esri/esri-leaflet-vector/issues/210), where there is a warning about an undefined listener.
Changes:
- Replace this undefined reference with a pointer to MapGL's resize function.
- Two small comment text changes
> Reference GL Map resize function in place of undefined reference

- examples/basemap-places.html
- examples/languages.html
- examples/worldview.html
- spec/VectorBasemapLayerSpec.js
- src/Util.js
- src/VectorBasemapLayer.js
connected issue: #213 
This PR currently adds support for the `worldview` parameter. I also added support for the `places` parameter, but requesting places through esri leaflet is currently resulting in the following styling error:
This error will need to be investigated further. I am sure how to fix this off the top of my head.
> add worldview and places params

- package-lock.json
- package.json
Haven't done much more than #201 did
Just updated the peerDependency, and made sure v4 is resolved in the lockfile.
Test results – though I'm not sure the `maplibre-gl` integration is actually covered by tests:
> Support `maplibre-gl` v4

- examples/contour-dev.html
- examples/custom-vtl-dev.html
- examples/gallery-dev.html
- examples/quickstart-dev.html
This is only in `console.log`s in the demo pages.
> fix version display for maplibregl v4

- CHANGELOG.md
backport maplibre versions into changelog
> Changelog: maplibre versions

- spec/VectorBasemapLayerSpec.js
- src/VectorBasemapLayer.js
Issue: #228 
In #135 we added add call to `Util.setEsriAttribution()` to add the "Powered by Esri" attribution, but after Esri Leaflet v3.0.10, calling `Util.setEsriAttribution` does not add "Powered by Esri" anymore. Esri Leaflet only adds "Powered by Esri" for dynamic attribution situations now. So now for non-dynamic situations, we must add the string ourselves.
After this gets released: https://github.com/Esri/esri-leaflet/pull/1397 ... we could use that function so that we do not need to hardcode that string here. But for now I'm adding it since I want to get this in before waiting for an Esri Leaflet release.
> add back "Powered by Esri" attribution for vectorBasemapLayer when using an item ID

- src/MaplibreGLLayer.js
- src/VectorBasemapLayer.js
Improved console error message for invalid API Key
#158 
Cc @gavinr-maps
> API Key console error clarification

- CHANGELOG.md
- package-lock.json
https://github.com/maplibre/maplibre-gl-js/releases/tag/v4.7.1
> update maplibre-gl version to 4.7.1

- examples/custom-vtl-dev.html
- spec/UtilSpec.js
- src/Util.js
This PR adds support for switching URLs for the style, sprites and glyphs to the CDN. This should reduce load times and load on the database since this will cache token validation at the edge in the cache key.
This should only apply to `VectorTileLayer`s loaded with a custom item id. If a service URL is used then this should apply to sprites and glyph but no the style URL. This approach should work for all ArcGIS Online items.
> Switch to use CDN URLs for style, sprite and glyph URLs
